#!/bin/bash

function ubahn() {
  OUTPUT=`ubahn-wrapper $@`
  if [ $? -eq 42 ]
  then cd "$OUTPUT"
  else echo "$OUTPUT"
  fi
}
### ubahn completion - begin. generated by omelette.js ###
if type compdef &>/dev/null; then
  _ubahn_complette() {
    compadd -- `ubahn --compzsh --compgen "${CURRENT}" "${words[CURRENT-1]}" "${BUFFER}"`
  }
  compdef _ubahn_complette ubahn
elif type complete &>/dev/null; then
  _ubahn_complette() {
    COMPREPLY=( $(compgen -W '$(ubahn --compbash --compgen "${COMP_CWORD}" "${COMP_WORDS[COMP_CWORD-1]}" "${COMP_LINE}")' -- "${COMP_WORDS[COMP_CWORD]}") )
  }
  complete -F _ubahn_complette ubahn
fi
### ubahn completion - end ###
### ub completion - begin. generated by omelette.js ###
if type compdef &>/dev/null; then
  _ub_complette() {
    compadd -- `ubahn --compzsh --compgen "${CURRENT}" "${words[CURRENT-1]}" "${BUFFER}"`
  }
  compdef _ub_complette ub
elif type complete &>/dev/null; then
  _ub_complette() {
    COMPREPLY=( $(compgen -W '$(ubahn --compbash --compgen "${COMP_CWORD}" "${COMP_WORDS[COMP_CWORD-1]}" "${COMP_LINE}")' -- "${COMP_WORDS[COMP_CWORD]}") )
  }
  complete -F _ub_complette ub
fi
### ub completion - end ###
